train:
  _target_: src.datasets.ASVSpoof2021LADataset
  part: "train"
  audio_dir: "data/ASVspoof2021LA"
  limit: 320
dev:
  _target_: src.datasets.ASVSpoof2021LADataset
  part: "dev"
  audio_dir: "data/ASVspoof2021LA"
  limit: 320
  shuffle: False
